name: Notify mlops-prod

on:
  push:
    branches: [main]  # ou outra branch que representa produção

jobs:
  notify-mlops:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger main-repo-subtrees via repository_dispatch
        env:
          GH_TOKEN: ${{ secrets.MLOPS_PROD_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/anafsouza/main-repo-subtrees/dispatches \
            -d '{"event_type": "update-from-subrepo-number-2"}'
          echo "Notification sent to main-repo-subtrees for subrepo-number-2 update."
